/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Firmware version
         * @description The three-part split of the firmware version, which is derived from
         *     `git describe` at build time. A describe output that is not a
         *     three-part semver — an untagged build, for instance — reports
         *     `0.0.0` rather than inventing a version from the hash.
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Firmware identity and health
         * @description Public, like every other `GET`: it carries no credential and no
         *     program data, only the firmware's own identity and health.
         *
         *     The coredump itself is deliberately **not** exposed — it is a raw RAM
         *     snapshot and can contain the WiFi password, so retrieving one stays an
         *     out-of-band job needing physical access. `coredumpPresent` only says
         *     whether there is something to go and fetch.
         *
         *     `startupIssues` is the one field here that is not a health counter: it
         *     is the set of `backend_issue` events the device raised before this
         *     server existed, which the SSE stream could not deliver to anybody. A
         *     client that wants to know whether a stored program failed to load has
         *     to ask for them; nothing pushes them.
         */
        get: operations["getDiagnosticsInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin-mode/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether admin mode is on */
        get: operations["getAdminModeStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin-mode/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn admin mode on and open a session
         * @description Sets the password — any non-empty string, chosen by this call — and
         *     returns the first session token. Refused while admin mode is already
         *     on: log in or disable it first.
         */
        post: operations["enableAdminMode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin-mode/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open another session with the active password */
        post: operations["loginAdminMode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin-mode/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate the presenting session
         * @description Ends this session only, leaving admin mode on — which is what a client
         *     walking away from a shared range laptop wants, and the opposite of
         *     `disable`.
         *
         *     The token is taken from the `Authorization` header, falling back to
         *     the `admin` cookie. **This endpoint is not itself protected**: it
         *     always answers `200` and always clears the cookie, whether or not the
         *     presented token was a live session (or was presented at all).
         */
        post: operations["logoutAdminMode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin-mode/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn admin mode off
         * @description Clears the password and invalidates every issued token. Note this
         *     turns protection *off* — every endpoint becomes writable by anyone on
         *     the network again. It is not "log out"; see `/admin-mode/logout`.
         */
        post: operations["disableAdminMode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the stored programs
         * @description Summaries only — the series are omitted. Ordered by id ascending.
         */
        get: operations["listPrograms"];
        put?: never;
        /**
         * Upload a program
         * @description The `id` in the uploaded document is **ignored**: the device assigns
         *     the next free id from 100 upwards and rewrites the file from the
         *     parsed program, so what is persisted is what will come back on the
         *     next boot. `readonly` in the document is ignored too — it follows from
         *     the directory the program lives in, and an upload is never read-only.
         *
         *     Unknown fields are dropped, and `duration` is clamped to
         *     1…3600000 ms per event. Posting a document carrying an existing id
         *     creates a *new* program; replacing one is `PUT /programs/{id}`.
         */
        post: operations["createProgram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Program id. Must be a plain decimal integer within `int32`; anything else is a `404` rather than being read as id 0. */
                id: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** Fetch one program in full */
        get: operations["getProgram"];
        /**
         * Replace an uploaded program
         * @description Replaces the stored document for `{id}` with the body, parsed and
         *     validated exactly as `POST /programs` parses an upload and rewritten
         *     from the parsed model — so unknown fields are dropped, `duration` is
         *     clamped to 1…3600000 ms per event, and `readonly` in the body is
         *     ignored. The response is the stored form, identical to what
         *     `GET /programs/{id}` returns afterwards.
         *
         *     The id never moves: `{id}` in the path is the authority, matching the
         *     filename the program is stored under. A body carrying an `id` other
         *     than `{id}` is a `400` rather than a rename or a renumbering; a body
         *     with no `id` (or `id: null`) is accepted and keeps `{id}`.
         *
         *     **The program must not be loaded.** Run state holds a pointer into the
         *     stored program, so replacing a loaded one would swap the series out
         *     from beneath a run in progress and beneath the indices already
         *     published over `stateUpdate`. The client calls
         *     `POST /programs/unload` (or loads something else) first; there is no
         *     forced-update flag.
         */
        put: operations["updateProgram"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}/load": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Program id. Must be a plain decimal integer within `int32`; anything else is a `404` rather than being read as id 0. */
                id: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select a program to run
         * @description Selects the program at series 0, event 0, with `tickerMs` unset. Does not start it.
         */
        post: operations["loadProgram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Program id. Must be a plain decimal integer within `int32`; anything else is a `404` rather than being read as id 0. */
                id: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an uploaded program
         * @description Shipped programs are read-only and answer `409`, the same refusal
         *     `PUT /programs/{id}` gives for the same program — a program that does
         *     not exist is the `404`. Deletability is checked before anything is
         *     unloaded, so a refused delete never disturbs a run in progress. If the
         *     program being deleted is the loaded one, it is unloaded first
         *     (whatever the run state — see `POST /programs/unload`) and a
         *     `stateUpdate` follows.
         */
        delete: operations["deleteProgram"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start the named program, if it is the one loaded
         * @description Resumes the current series from `tickerMs`, or runs it from zero
         *     when the ticker is unset. Starting an already-running program is a
         *     no-op and still answers `200`. Audio only replays when the resume
         *     point lands exactly on an event boundary.
         *
         *     The body names the program the caller decided to start, and the device
         *     refuses with `409` if it holds a different one (D-27). The id is
         *     **required**: an id-less start asks the device to run whatever it
         *     happens to hold at that instant, which is the ambiguity this closes.
         */
        post: operations["startProgram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause the running program
         * @description Pauses and keeps the last published position, so `start` resumes from it. That is the ticker the last `stateUpdate` carried, not the instant the pause arrived. Since `asyncapi.yaml` 3.0.0 replaced the whole-second `tickerSeconds` with `tickerMs`, a pause a few hundred milliseconds into a series no longer rewinds to the start of it.
         */
        post: operations["stopProgram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rewind to the start of the current series
         * @description Stops the run, selects event 0 of the current series and clears `tickerMs`. The selected series is kept.
         */
        post: operations["resetProgram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/unload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear the loaded program
         * @description Clears the selection and publishes a `stateUpdate` carrying
         *     `loadedProgramId: null` and `programState: null`. The targets are left
         *     exactly where the run left them — unloading moves no hardware.
         *
         *     **Refused while a run is in progress** (`409`): unloading is
         *     bookkeeping, and a call that reads as bookkeeping must not end a series
         *     mid-range. `stop` first — it is a pause, so the refusal lifts with it.
         *
         *     **Idempotent.** Unloading when nothing is loaded is `200` with the same
         *     message; no `stateUpdate` follows, because it would repeat the one
         *     clients already hold. So a `200` means "nothing is loaded now", not
         *     "something was unloaded just now" — the two are not distinguishable,
         *     deliberately.
         *
         *     This is the escape from the `409` that `PUT /programs/{id}` and
         *     `DELETE /audios/{id}/delete` point at when the program that blocks them
         *     is the loaded one.
         */
        post: operations["unloadProgram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/series/{seriesIndex}/skip_to": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Zero-based index into the loaded program's `series`. Must be a plain decimal integer; anything else is a `404`. */
                seriesIndex: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Jump to a series
         * @description Stops the run and selects the series, paused at its first event with `tickerMs` cleared.
         */
        post: operations["skipToSeries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn the targets face-on
         * @description Drives the target hardware directly. It does not stop a running program, which will move the targets again at its next event boundary.
         */
        post: operations["showTargets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn the targets edge-on */
        post: operations["hideTargets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flip the targets */
        post: operations["toggleTargets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the stored audio clips */
        get: operations["listAudios"];
        put?: never;
        /**
         * Upload an audio clip
         * @description A `multipart/form-data` body with one file part and a `title` field.
         *
         *     The client's filename is never used on disk: only its `.wav`
         *     extension is checked, as an early reject, and the clip is streamed to
         *     a fixed staging file, validated, and renamed to `<id>.wav` once an id
         *     is assigned. Every failure path removes the staging file, so a
         *     repeated failed upload cannot fill the partition.
         *
         *     Accepted audio is RIFF/WAVE, PCM (format tag 1), 16-bit, mono or
         *     stereo, with a non-zero sample rate and a non-empty `data` chunk.
         *     Chunks are walked rather than assumed, so a `LIST`/`INFO` chunk before
         *     `data` is fine.
         *
         *     There is one staging slot, but no upload is ever refused for it: the
         *     server handles requests one at a time, so two uploads never overlap. A
         *     new upload always proceeds, starting by discarding anything an
         *     interrupted upload left staged — so an upload whose connection dies
         *     mid-body leaves nothing behind and cannot corrupt the next one.
         *
         *     Two details of the vendored HTTP layer, recorded because clients rely
         *     on them in practice: the part name of the file is not inspected (any
         *     name works), and `title` is matched as a non-`POST` parameter, so it
         *     may equally be supplied as a `?title=` query parameter.
         */
        post: operations["createAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audios/{id}/play": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Audio clip id. Must be a plain decimal integer within `int32`. */
                id: components["parameters"]["AudioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Play a clip now
         * @description Acknowledged immediately and played on the audio task — the response is not held open for the length of the clip.
         */
        post: operations["playAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audios/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Audio clip id. Must be a plain decimal integer within `int32`. */
                id: components["parameters"]["AudioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an uploaded clip
         * @description Shipped clips are read-only and answer `409`; only a clip that does not
         *     exist is a `404`.
         *
         *     A clip that matters to a run cannot be deleted: a spoken command that
         *     silently fails mid-exercise is a range-safety problem. Refusal order,
         *     most specific reason first, and existence before all of them so a bogus
         *     id is never reported as a conflict:
         *
         *     1. no such clip — `404`
         *     2. it is shipped with the firmware — `409` (the reason that never lifts)
         *     3. the loaded program plays it — `409`
         *     4. a run is in progress — `409`
         *     5. the audio task is reading it right now — `409`
         */
        delete: operations["deleteAudio"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sse/v2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The run-state event stream
         * @description Public, and specified in full in `contracts/asyncapi.yaml`: a
         *     `stateUpdate` on connect and after every mutation, a `heartbeat`
         *     every 10 seconds, and a `backend_issue` whenever the device hits a
         *     failure no request can be answered with.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description An RFC 9457 problem detail — the shape every handler uses for a
         *     failure, served as `application/problem+json` (D-19). The one
         *     exception is a request body over the size ceiling, rejected by the
         *     HTTP layer with a `text/html` body.
         *
         *     RFC 9457 permits extension members; this device emits none, which is
         *     what `additionalProperties: false` records.
         */
        Problem: {
            /**
             * Format: uri-reference
             * @description The problem type — **the member to branch on**. A stable relative
             *     URI that is never dereferenced.
             *
             *     The enum is the whole vocabulary. It is open in practice: a client
             *     must fall back to `status` and `detail` for a value it does not
             *     recognise, because new types are additive and a client may be
             *     older than the firmware it is talking to.
             *
             *     `/problems/program_invalid` is deliberately the same slug as the
             *     `program_invalid` `backend_issue` code in `asyncapi.yaml`.
             * @enum {string}
             */
            type: "/problems/admin_credentials_required" | "/problems/invalid_password" | "/problems/route_not_found" | "/problems/program_not_found" | "/problems/audio_not_found" | "/problems/admin_mode_already_enabled" | "/problems/admin_mode_not_enabled" | "/problems/no_program_loaded" | "/problems/program_not_running" | "/problems/program_running" | "/problems/program_loaded" | "/problems/start_program_mismatch" | "/problems/program_readonly" | "/problems/audio_readonly" | "/problems/audio_in_use" | "/problems/audio_playing" | "/problems/program_invalid" | "/problems/program_id_mismatch" | "/problems/series_index_invalid" | "/problems/start_id_required" | "/problems/upload_missing_file" | "/problems/upload_missing_title" | "/problems/audio_format_unsupported" | "/problems/program_store_failed" | "/problems/audio_store_failed";
            /**
             * @description A short summary of the type, identical for every occurrence of it. Not for display — it does not describe this occurrence.
             * @example Program is read-only
             */
            title: string;
            /** @description The HTTP status, repeated in the body. One status per `type`, always, and always the status on the response line. */
            status: number;
            /**
             * @description What went wrong on this occurrence. This is the string to show a user, and the only member whose wording may change without a contract change — never branch on it.
             * @example Program is read-only and cannot be deleted
             */
            detail: string;
        };
        /** @description The shape every handler uses for a plain success. */
        Message: {
            message: string;
        };
        CreatedId: {
            /**
             * Format: int32
             * @description The id the device assigned. Uploaded programs and clips are numbered from 100 upwards, keeping them clear of the shipped ids.
             */
            id: number;
        };
        /** @description The program the caller decided to start. Required, and required to be an integer: a start with no id, or with an `id` of another type, is a `400` rather than a start of whatever happens to be loaded. */
        StartRequest: {
            /**
             * Format: int32
             * @description The program the client last saw loaded and armed the start for.
             */
            id: number;
        };
        /** @description A missing, unparseable or non-string `password` is treated as an empty password, which is refused with `401`. */
        PasswordBody: {
            password: string;
        };
        Version: {
            major: number;
            minor: number;
            patch: number;
        };
        ProgramSummary: {
            /** Format: int32 */
            id: number;
            title: string;
            description: string;
            /** @description True for programs flashed with the firmware. Read-only programs cannot be deleted or updated. */
            readonly: boolean;
        };
        /** @description The full program document. Kept in lock-step with `contracts/program.schema.json`, which is the authoring schema for the files in `resources/programs/files/`. */
        Program: {
            /** Format: int32 */
            id: number;
            title: string;
            description: string;
            readonly: boolean;
            series: components["schemas"]["Series"][];
        };
        /** @description The body of `PUT /programs/{id}`. `Program` with `id` made optional: the path is the authority on the id, so a body may leave it out entirely, and one declaring anything other than `{id}` is a `400`. Spelled out rather than referenced because a JSON Schema `allOf` cannot relax a `required` its base declares. */
        ProgramUpdate: {
            /**
             * Format: int32
             * @description Optional. If present it must equal `{id}` in the path.
             */
            id?: number;
            title: string;
            description: string;
            /** @description Ignored; it follows from where the device stores the file. */
            readonly: boolean;
            series: components["schemas"]["Series"][];
        };
        Series: {
            name: string;
            /** @description Carried through the API but not acted on by the run loop: the executor runs one series at a time and never skips one by itself. */
            optional: boolean;
            events: components["schemas"]["Event"][];
        };
        /** @description One step: hold for `duration`, moving the targets and playing audio on entry. On the wire, `command` and `audio_ids` are omitted when empty. */
        Event: {
            /**
             * Format: int32
             * @description Milliseconds. Clamped to 1…3600000 on parse, so a `0` or negative value becomes 1 ms and an absurd one is capped rather than overflowing the series total.
             */
            duration: number;
            /**
             * @description What to do with the targets on entering this event. Optional: omit it for a timed pause that leaves the targets where they are. When it is present it must be `show` or `hide` — the device refuses the whole program with `400` otherwise, so that a typo such as `shwo` fails at upload instead of becoming a target that silently never turns mid-exercise.
             *
             *     For compatibility with the legacy program editor, which writes `null` for its "no change" option, the device also accepts `null` and the empty string in place of omission. Neither is part of this schema and neither is ever emitted: an event with no command has no `command` key.
             * @enum {string}
             */
            command?: "show" | "hide";
            /** @description Clips to start on entering this event. Ids that no longer exist are skipped. */
            audio_ids?: number[];
        };
        AudioList: {
            audios: components["schemas"]["Audio"][];
        };
        Audio: {
            /** Format: int32 */
            id: number;
            title: string;
            /** @description The absolute path on the device's LittleFS mount, e.g. `/storage/shipped/audio/26.wav`. Named `filename` for compatibility with the MicroPython backend, which joined the directory into it the same way. */
            filename: string;
            /** @description True for clips flashed with the firmware. */
            readonly: boolean;
        };
        PartitionInfo: {
            /** @description The partition label from `partitions.csv`, e.g. `storage`. */
            name: string;
            /** @enum {string} */
            kind: "app" | "data";
            /** @description The slot's size, from the partition table. */
            sizeBytes: number;
            /** @description Absent where the device cannot tell. Present for the app slots (the length of the image on flash, walked from its header), the LittleFS partition, NVS (a whole number of 32-byte entries, so it is granular rather than exact) and the coredump partition (0 when no dump is stored). */
            usedBytes?: number;
            /** @description App partitions only — whether this is the slot the device booted from. */
            running?: boolean;
        };
        DiagnosticsInfo: {
            /** @description `git describe` output, e.g. `2.0.0-3-gab12cde`. */
            version: string;
            /** @description The ESP-IDF version the firmware was built against. */
            idfVersion: string;
            /** @description Compiler date and time, e.g. `Aug 19 2026 11:42:03`. */
            buildDate: string;
            /** @enum {string} */
            resetReason: "poweron" | "external" | "software" | "panic" | "interrupt_watchdog" | "task_watchdog" | "other_watchdog" | "deepsleep" | "brownout" | "sdio" | "usb" | "jtag" | "efuse" | "power_glitch" | "cpu_lockup" | "unknown";
            uptimeSeconds: number;
            freeHeapBytes: number;
            /** @description The low-water mark since boot, not the current figure: a leak that has already been reclaimed is invisible in the latter. */
            minFreeHeapBytes: number;
            freePsramBytes: number;
            /** @description The OTA partition label, e.g. `ota_0`, or `unknown`. */
            runningPartition: string;
            /** @description Whether a coredump image is waiting to be pulled out of band. The dump itself is never served. */
            coredumpPresent: boolean;
            /** @description The `storage` partition's size. Kept alongside `partitions`, which reports the same figure — this pair predates it and clients still read it. */
            storageTotalBytes: number;
            storageUsedBytes: number;
            /** @description Every partition in the flash table, in flash-offset order. `storage` is not the only one that can fill: the app slots decide whether an over-the-air image will fit, and NVS holds the provisioned credentials. */
            partitions: components["schemas"]["PartitionInfo"][];
            programCount: number;
            audioCount: number;
            /** @description The device's current address, or empty when it has none. */
            ipAddress: string;
            /** @description The GPIO number the target hardware is wired to. */
            targetGpio: number;
            /** @description The level actually on the pad, read back rather than remembered — the pair with `targetGpio` distinguishes "the firmware never drove it" from "something else is holding it". */
            targetGpioLevel: number;
            adminModeEnabled: boolean;
            /**
             * @description The `backend_issue` events raised during boot, before the HTTP
             *     server was listening — today that is `program_invalid` from the
             *     program scan, which runs several steps ahead of the server. The SSE
             *     stream is fire-and-forget (see `contracts/asyncapi.yaml`), so those
             *     frames reached nobody: a stored program that would not parse simply
             *     disappeared from `GET /programs`, explained only on the serial
             *     console.
             *
             *     Empty on a clean boot, which is the normal case. **At most 8
             *     entries**, oldest dropped, so an array of exactly 8 may be a
             *     truncated one; the device log remains the complete record.
             *
             *     Written once during boot and read-only afterwards — the list does
             *     not grow while the device is up, and polling it will not show
             *     anything new until the next reboot. Run-time failures such as
             *     `audio_playback_failed` never appear here: they have a client to go
             *     to and are delivered over SSE.
             */
            startupIssues: components["schemas"]["StartupIssue"][];
        };
        /** @description One boot-time device-side failure. Deliberately the same shape as the SSE `backend_issue` payload in `contracts/asyncapi.yaml`, with the same `code` vocabulary, so a client has one way to describe a device failure rather than two. */
        StartupIssue: {
            /**
             * @description The machine-readable identifier, from the same open set as
             *     `backend_issue.code` — tolerate a value this document does not
             *     list. Only codes that can be raised before the server exists appear
             *     here, which today is one:
             *
             *     - `program_invalid` — a file in a program directory could not be
             *       read or did not parse and was skipped, so the program is absent
             *       from `GET /programs`.
             */
            code: string;
            /** @description English prose describing the failure, suitable for a banner. Not stable across releases and not to be parsed. */
            message: string;
            /** @description What failed. Present whenever the emitter has something to name; keys depend on `code`. */
            context?: {
                /** @description `program_invalid`: the program file's path on the device filesystem. */
                file?: string;
            } & {
                [key: string]: string;
            };
        };
    };
    responses: {
        /**
         * @description - `/problems/admin_credentials_required` — admin mode is on and no
         *       valid token was presented.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A session token, also set as a cookie. */
        AdminSession: {
            headers: {
                /** @description `admin=<token>; Path=/; SameSite=Lax` */
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description 32 hex characters (16 random bytes). */
                    token: string;
                };
            };
        };
    };
    parameters: {
        /** @description Program id. Must be a plain decimal integer within `int32`; anything else is a `404` rather than being read as id 0. */
        ProgramId: number;
        /** @description Audio clip id. Must be a plain decimal integer within `int32`. */
        AudioId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The running firmware version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    getDiagnosticsInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A health snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsInfo"];
                };
            };
        };
    };
    getAdminModeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether write protection is currently enabled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        enabled: boolean;
                    };
                };
            };
        };
    };
    enableAdminMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordBody"];
            };
        };
        responses: {
            200: components["responses"]["AdminSession"];
            /**
             * @description - `/problems/invalid_password` — the password was empty, or the
             *       body carried none.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description - `/problems/admin_mode_already_enabled` — log in or disable it
             *       first.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    loginAdminMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordBody"];
            };
        };
        responses: {
            200: components["responses"]["AdminSession"];
            /** @description - `/problems/invalid_password` — wrong password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description - `/problems/admin_mode_not_enabled` — there is nothing to log in
             *       to.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logoutAdminMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. `Set-Cookie: admin=; Path=/; SameSite=Lax; Max-Age=0` clears the cookie. */
            200: {
                headers: {
                    /** @description Clears the `admin` cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    disableAdminMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin mode disabled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPrograms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every program the device holds, shipped and uploaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramSummary"][];
                };
            };
        };
    };
    createProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A program document; see `contracts/program.schema.json`. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Program"];
            };
        };
        responses: {
            /** @description Stored. The body carries the assigned id. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
            /**
             * @description - `/problems/program_invalid` — empty body, malformed JSON, or a
             *       non-object root.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProgram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Program id. Must be a plain decimal integer within `int32`; anything else is a `404` rather than being read as id 0. */
                id: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The program, series and events included. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"];
                };
            };
            /**
             * @description - `/problems/program_not_found` — no such program, or a path
             *       segment that is not a plain decimal integer.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateProgram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Program id. Must be a plain decimal integer within `int32`; anything else is a `404` rather than being read as id 0. */
                id: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        /** @description A program document; see `contracts/program.schema.json`. `id` may be omitted, and `readonly` is ignored. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramUpdate"];
            };
        };
        responses: {
            /** @description Replaced. The body is the program as stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"];
                };
            };
            /**
             * @description - `/problems/program_invalid` — empty body, malformed JSON, or a
             *       non-object root.
             *     - `/problems/program_id_mismatch` — the body declares a different
             *       id from the path.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description - `/problems/program_not_found` — no such program, or a path
             *       segment that is not a plain decimal integer.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description - `/problems/program_readonly` — the program is shipped with the
             *       firmware and has no writable file behind it. Upload the document
             *       as a new program instead.
             *     - `/problems/program_loaded` — it is the loaded program.
             *       `POST /programs/unload` first.
             *
             *     The same status for two refusals a client must answer differently
             *     is why `type` exists (D-19): the wording of `detail` is not a
             *     discriminator.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description - `/problems/program_store_failed` — the replacement could not be
             *       written to flash. The previous document is left intact.
             */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    loadProgram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Program id. Must be a plain decimal integer within `int32`; anything else is a `404` rather than being read as id 0. */
                id: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Program loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description - `/problems/program_not_found` — no such program.
             *     - `/problems/route_not_found` — the path did not parse.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteProgram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Program id. Must be a plain decimal integer within `int32`; anything else is a `404` rather than being read as id 0. */
                id: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Program deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description - `/problems/program_not_found` — no such program.
             *     - `/problems/route_not_found` — the path did not parse.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description - `/problems/program_readonly` — the program is shipped with the
             *       firmware and has no writable file behind it. The same type
             *       `PUT /programs/{id}` answers for the same program.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    startProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Program started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /**
             * @description - `/problems/no_program_loaded` — nothing is loaded, or the loaded
             *       program has no series at the current index.
             *     - `/problems/start_id_required` — no body, unparseable JSON, or no
             *       integer `id`.
             *
             *     "Nothing is loaded" outranks the id check: it is the more precise
             *     diagnosis, and it is what a client that has to load something first
             *     needs to hear.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description - `/problems/start_program_mismatch` — a different program is
             *       loaded. `detail` names both ids, because the operator needs to
             *       know what the device actually holds to decide what to do about
             *       it. The run state is untouched and no `stateUpdate` is published.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stopProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Program paused. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description - `/problems/program_not_running` — nothing is running. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    resetProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Program reset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description - `/problems/no_program_loaded` — nothing is loaded. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    unloadProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nothing is loaded. Either it was just unloaded (a `stateUpdate` follows) or nothing was loaded to begin with (none does). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description - `/problems/program_running` — a run is in progress. `stop` first;
             *       it is a pause, so the refusal lifts with it.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    skipToSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Zero-based index into the loaded program's `series`. Must be a plain decimal integer; anything else is a `404`. */
                seriesIndex: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skipped to series <index>. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /**
             * @description - `/problems/series_index_invalid` — nothing is loaded, or the
             *       index is outside the loaded program. The firmware does not
             *       distinguish the two.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description - `/problems/route_not_found` — the path segment is not a plain
             *       decimal integer.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    showTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Targets shown. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    hideTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Targets hidden. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    toggleTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resulting state, as `Targets shown` or `Targets hidden`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAudios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every clip the device holds, shipped and uploaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioList"];
                };
            };
        };
    };
    createAudio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The clip. The filename must end in `.wav`.
                     */
                    file: string;
                    /** @description Display title. May also be given in the query string. */
                    title: string;
                };
            };
        };
        responses: {
            /** @description Stored. The body carries the assigned id. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
            /**
             * @description - `/problems/upload_missing_file` — no file part arrived.
             *     - `/problems/upload_missing_title` — the `title` field is absent
             *       or empty.
             *     - `/problems/audio_format_unsupported` — not a playable PCM 16-bit
             *       WAV.
             *
             *     A body over the 1 MiB ceiling is also answered `400`, but with a
             *     `text/html` body rather than a problem detail.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description - `/problems/audio_store_failed` — the clip could not be moved
             *       into place or indexed.
             */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    playAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Audio clip id. Must be a plain decimal integer within `int32`. */
                id: components["parameters"]["AudioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playback started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Playback started";
                        /** Format: int32 */
                        audioId: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description - `/problems/audio_not_found` — no such clip.
             *     - `/problems/route_not_found` — the path did not parse.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Audio clip id. Must be a plain decimal integer within `int32`. */
                id: components["parameters"]["AudioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audio deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description - `/problems/audio_not_found` — no such clip.
             *     - `/problems/route_not_found` — the path did not parse.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description The clip is shipped, or it still matters to a run. Four types
             *     under one status, in the order the firmware checks them:
             *
             *     - `/problems/audio_readonly` — shipped with the firmware, so there
             *       is no file of ours to remove. Checked first: it is the only one
             *       of these reasons that never lifts.
             *     - `/problems/audio_in_use` — an event of the loaded program plays
             *       it. Refused whether or not a run is in progress: `stop` is a
             *       pause, so a clip deleted between two runs would be missing when
             *       the program resumes. "Unload" is `POST /programs/unload`.
             *     - `/problems/program_running` — a run is in progress. Refused for
             *       every clip, referenced or not. The same type
             *       `POST /programs/unload` answers, because it is the same
             *       condition.
             *     - `/problems/audio_playing` — the audio task is reading the file
             *       right now. LittleFS has no unlink-while-open, so removing it
             *       would corrupt the read.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An open `text/event-stream`, with `Cache-Control: no-cache` and `Connection: keep-alive`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
