#include "audio.h"

#include <cstdio>
#include <cstring>

#include "config.h"
#include "driver/i2s_std.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/task.h"

namespace audio {
namespace {

const char *TAG = "audio";

i2s_chan_handle_t s_tx = nullptr;
QueueHandle_t s_queue = nullptr;
// Guards s_tx across the reconfigure/enable/disable a clip does, so a queued
// clip cannot start while the previous one is tearing down.
SemaphoreHandle_t s_i2s_lock = nullptr;

// One queued playlist. Sent by pointer through the queue and deleted by the
// playback task.
using Playlist = std::vector<std::string>;

uint32_t read_le(const uint8_t *p, size_t bytes) {
  uint32_t v = 0;
  for (size_t i = 0; i < bytes; i++) v |= static_cast<uint32_t>(p[i]) << (8 * i);
  return v;
}

// Walks the RIFF chunks rather than assuming a 44-byte header: the shipped
// clips are generated by a TTS pipeline that emits a LIST/INFO chunk before
// `data`, and a fixed 44-byte skip would play that metadata as samples.
bool parse_header(FILE *f, WavInfo &out) {
  uint8_t riff[12];
  if (fread(riff, 1, sizeof(riff), f) != sizeof(riff)) return false;
  if (memcmp(riff, "RIFF", 4) != 0 || memcmp(riff + 8, "WAVE", 4) != 0) return false;

  bool have_fmt = false;
  uint8_t chunk[8];
  while (fread(chunk, 1, sizeof(chunk), f) == sizeof(chunk)) {
    const uint32_t size = read_le(chunk + 4, 4);

    if (memcmp(chunk, "fmt ", 4) == 0) {
      uint8_t fmt[16];
      if (size < sizeof(fmt) || fread(fmt, 1, sizeof(fmt), f) != sizeof(fmt)) return false;

      const uint16_t audio_format = static_cast<uint16_t>(read_le(fmt, 2));
      out.channels = static_cast<uint16_t>(read_le(fmt + 2, 2));
      out.sample_rate = read_le(fmt + 4, 4);
      const uint16_t bits = static_cast<uint16_t>(read_le(fmt + 14, 2));

      if (audio_format != 1 || bits != 16 || (out.channels != 1 && out.channels != 2)) {
        ESP_LOGW(TAG, "Unsupported WAV: format=%u channels=%u bits=%u", audio_format, out.channels,
                 bits);
        return false;
      }
      have_fmt = true;
      // Chunks are word-aligned and fmt may be longer than the 16 bytes read.
      if (fseek(f, static_cast<long>(size - sizeof(fmt) + (size & 1)), SEEK_CUR) != 0) return false;
    } else if (memcmp(chunk, "data", 4) == 0) {
      if (!have_fmt) return false;
      out.data_offset = static_cast<uint32_t>(ftell(f));
      out.data_bytes = size;
      return true;
    } else {
      if (fseek(f, static_cast<long>(size + (size & 1)), SEEK_CUR) != 0) return false;
    }
  }
  return false;
}

void play_one(const std::string &path) {
  WavInfo info;
  FILE *f = fopen(path.c_str(), "rb");
  if (f == nullptr) {
    ESP_LOGE(TAG, "Cannot open %s", path.c_str());
    return;
  }
  if (!parse_header(f, info) || fseek(f, static_cast<long>(info.data_offset), SEEK_SET) != 0) {
    ESP_LOGE(TAG, "Not a playable WAV: %s", path.c_str());
    fclose(f);
    return;
  }

  xSemaphoreTake(s_i2s_lock, portMAX_DELAY);

  // Clips are generated at a range of sample rates, so the clock is set per
  // clip rather than once at init.
  i2s_std_clk_config_t clk = I2S_STD_CLK_DEFAULT_CONFIG(info.sample_rate);
  if (i2s_channel_reconfig_std_clock(s_tx, &clk) != ESP_OK || i2s_channel_enable(s_tx) != ESP_OK) {
    ESP_LOGE(TAG, "I2S setup failed for %s", path.c_str());
    xSemaphoreGive(s_i2s_lock);
    fclose(f);
    return;
  }

  // static, not stack: together these are 3 KB, which a 4 KB task stack cannot
  // hold alongside its call frames. Safe because play_one() only ever runs on
  // the single playback task.
  static uint8_t chunk[kAudioChunkBytes];
  // Mono is duplicated into both channels, so the write buffer is twice the
  // read buffer - the PCM5102A is wired as a stereo DAC either way.
  static uint8_t stereo[kAudioChunkBytes * 2];
  uint32_t remaining = info.data_bytes;

  while (remaining > 0) {
    const size_t want = remaining < sizeof(chunk) ? remaining : sizeof(chunk);
    const size_t got = fread(chunk, 1, want, f);
    if (got == 0) break;
    remaining -= got;

    const uint8_t *out = chunk;
    size_t out_bytes = got;
    if (info.channels == 1) {
      for (size_t i = 0; i + 1 < got; i += 2) {
        stereo[i * 2 + 0] = chunk[i];
        stereo[i * 2 + 1] = chunk[i + 1];
        stereo[i * 2 + 2] = chunk[i];
        stereo[i * 2 + 3] = chunk[i + 1];
      }
      out = stereo;
      out_bytes = got * 2;
    }

    size_t written = 0;
    i2s_channel_write(s_tx, out, out_bytes, &written, portMAX_DELAY);
  }

  i2s_channel_disable(s_tx);
  xSemaphoreGive(s_i2s_lock);
  fclose(f);
  ESP_LOGD(TAG, "Played %s", path.c_str());
}

void playback_task(void *) {
  Playlist *list = nullptr;
  while (true) {
    if (xQueueReceive(s_queue, &list, portMAX_DELAY) == pdTRUE && list != nullptr) {
      for (const std::string &path : *list) play_one(path);
      delete list;
      list = nullptr;
    }
  }
}

}  // namespace

bool probe_wav(const char *path, WavInfo &out) {
  FILE *f = fopen(path, "rb");
  if (f == nullptr) return false;
  const bool ok = parse_header(f, out);
  fclose(f);
  return ok;
}

bool init() {
  s_i2s_lock = xSemaphoreCreateMutex();
  // Depth 1: a playlist waiting to start is always superseded by a newer one
  // (see play()), so there is never a reason to hold more than one.
  s_queue = xQueueCreate(1, sizeof(Playlist *));
  if (s_i2s_lock == nullptr || s_queue == nullptr) return false;

  i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(kI2sPort, I2S_ROLE_MASTER);
  chan_cfg.auto_clear = true;
  if (i2s_new_channel(&chan_cfg, &s_tx, nullptr) != ESP_OK) {
    ESP_LOGE(TAG, "i2s_new_channel failed");
    return false;
  }

  i2s_std_config_t std_cfg = {
      .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(44100),
      .slot_cfg =
          I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO),
      .gpio_cfg =
          {
              .mclk = I2S_GPIO_UNUSED,
              .bclk = kI2sBckPin,
              .ws = kI2sLckPin,
              .dout = kI2sDinPin,
              .din = I2S_GPIO_UNUSED,
              .invert_flags = {false, false, false},
          },
  };
  if (i2s_channel_init_std_mode(s_tx, &std_cfg) != ESP_OK) {
    ESP_LOGE(TAG, "i2s_channel_init_std_mode failed");
    return false;
  }

  // Priority 5 keeps it above the httpd and run-loop tasks: an underrun is
  // audible on the range, a few ms of added REST latency is not.
  if (xTaskCreate(playback_task, "audio", 4096, nullptr, 5, nullptr) != pdPASS) {
    ESP_LOGE(TAG, "Failed to start playback task");
    return false;
  }

  ESP_LOGI(TAG, "I2S ready (BCK=%d WS=%d DIN=%d)", kI2sBckPin, kI2sLckPin, kI2sDinPin);
  return true;
}

void play(const std::vector<std::string> &paths) {
  if (s_queue == nullptr || paths.empty()) return;

  Playlist *list = new Playlist(paths);
  if (xQueueSend(s_queue, &list, 0) == pdTRUE) return;

  // Queue full: drop whatever was waiting and replace it. The newest request
  // is the one that matches where the run actually is.
  Playlist *stale = nullptr;
  if (xQueueReceive(s_queue, &stale, 0) == pdTRUE) delete stale;
  if (xQueueSend(s_queue, &list, 0) != pdTRUE) delete list;
}

}  // namespace audio
