#!/usr/bin/env bash
#
# Build the firmware for the QEMU simulator profile and boot it, with the guest
# HTTP port forwarded to the host.
#
#   . ~/esp/esp-idf-6.0.2/export.sh
#   firmware/scripts/run-qemu.sh
#
# Then open http://localhost:8080 - the real REST API, the real SSE stream and
# the real webapp, out of the same LittleFS image the board is flashed with.
# Ctrl-A X quits QEMU (Ctrl-C reaches the guest, not the emulator).
#
# Options:
#   --build-only     build, do not boot
#   --headless       boot with no terminal attached (CI); serial goes to stdout
#   --port <n>       host port to forward from (default 8080)
#
# QEMU is invoked directly rather than through `idf.py qemu`, which cannot
# express the machine this board needs - see the comments on the argument list
# below and docs/QEMU.md. The build half is still plain idf.py.
set -euo pipefail

FIRMWARE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${FIRMWARE_DIR}/build-qemu"
HOST_PORT=8080
BUILD_ONLY=0
HEADLESS=0

while [ $# -gt 0 ]; do
    case "$1" in
        --build-only) BUILD_ONLY=1; shift ;;
        --headless) HEADLESS=1; shift ;;
        --port) HOST_PORT="$2"; shift 2 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

if [ -z "${IDF_PATH:-}" ]; then
    echo "IDF_PATH is not set - run '. \$IDF_PATH/export.sh' first" >&2
    exit 1
fi

echo "==> Building the QEMU profile into ${BUILD_DIR}"
idf.py -C "${FIRMWARE_DIR}" -B "${BUILD_DIR}" \
    -D SDKCONFIG="${BUILD_DIR}/sdkconfig" \
    -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.qemu" \
    build

[ "${BUILD_ONLY}" -eq 1 ] && exit 0

SDKCONFIG="${BUILD_DIR}/sdkconfig"
sdkconfig_value() { sed -n "s/^$1=\(.*\)$/\1/p" "${SDKCONFIG}" | tr -d '"'; }

# Whatever the firmware was configured to listen on, and the flash size the
# partition table was laid out for. Reading both back keeps the forward and the
# image correct when someone changes them.
GUEST_PORT="$(sdkconfig_value CONFIG_RT_HTTP_PORT)"
FLASH_SIZE="$(sdkconfig_value CONFIG_ESPTOOLPY_FLASHSIZE)"

# `idf.py qemu` builds this itself; done here because everything after it is
# too. Every binary in flash_args, including the LittleFS image, goes in.
FLASH_IMAGE="${BUILD_DIR}/qemu_flash.bin"
echo "==> Merging the flash image (${FLASH_SIZE})"
(cd "${BUILD_DIR}" && python -m esptool --chip esp32s3 merge-bin \
    --output "${FLASH_IMAGE}" --pad-to-size "${FLASH_SIZE}" "@flash_args")

if ! command -v qemu-system-xtensa >/dev/null 2>&1; then
    echo "==> Installing qemu-xtensa"
    python "${IDF_PATH}/tools/idf_tools.py" install qemu-xtensa
    # shellcheck disable=SC1091  # generated by the installer above
    . "${IDF_PATH}/export.sh" >/dev/null
fi

QEMU_PSRAM_MB="${QEMU_PSRAM_MB:-8}"

QEMU_ARGS=(
    -M esp32s3
    # PSRAM size, and it has to match the board - the N16R8's 8 MB. `idf.py
    # qemu` hardcodes 32M; at that size PSRAM claims the entire external-memory
    # virtual address range, every flash mmap after it fails with
    # ESP_ERR_NOT_FOUND, and the app aborts in nvs_flash_init() before it
    # reaches the network.
    -m "${QEMU_PSRAM_MB}M"
    -drive "file=${FLASH_IMAGE},if=mtd,format=raw"
    # No is_octal here, deliberately: the QEMU profile builds for quad PSRAM
    # because the emulator's octal model segfaults. See sdkconfig.defaults.qemu.
    # Nothing feeds the task watchdog while the emulator is paused under a
    # debugger, and the interrupt watchdog fires on emulated timing artefacts.
    -global driver=timer.esp32s3.timg,property=wdt_disable,value=true
    # SLIRP user networking: the guest gets 10.0.2.15 over DHCP and is
    # reachable from the host only through this explicit forward.
    # model=open_eth is the MAC the CONFIG_RT_NET_OPENETH build drives.
    -nic "user,model=open_eth,id=lo0,hostfwd=tcp:127.0.0.1:${HOST_PORT}-:${GUEST_PORT}"
    -display none
)
#
# Deliberately absent: the eFuse drive `idf.py qemu` always attaches. Its image
# describes a chip revision v0.3 part, and on v0.3 the octal-PSRAM driver runs
# MSPI timing tuning - a path qemu-xtensa 9.2.2 segfaults in, silently, right
# after "Loaded app from partition". Without the drive QEMU's built-in eFuse
# reads back as v0.0, the tuning is skipped, and nothing in this firmware cares
# which revision it is told it is running on.

echo "==> Booting QEMU; the device will answer on http://localhost:${HOST_PORT}"

if [ "${HEADLESS}" -eq 1 ]; then
    # No terminal to attach: serial goes straight to stdout and QEMU never
    # reads stdin - a CI runner hands it EOF, and QEMU quits on that.
    exec qemu-system-xtensa "${QEMU_ARGS[@]}" -monitor none -serial file:/dev/stdout
fi

echo "    (guest port ${GUEST_PORT}; Ctrl-A X to quit)"
exec qemu-system-xtensa "${QEMU_ARGS[@]}" -serial mon:stdio
