#!/usr/bin/env python3
"""Pack directory trees into one blob plus a C index, for embedding in the app image.

    pack_assets.py <out.bin> <out_index.h> [[gz:]<mount>=<dir> ...]

Each `<mount>=<dir>` puts that directory's contents under `/<mount>` in the
embedded filesystem, so `webapp=../webapp/dist` makes `dist/index.html` reachable
as `/webapp/index.html`. A directory that does not exist is skipped, which is how
an API-only build (no `webapp/dist`) produces an empty filesystem rather than a
build failure.

The `gz:` prefix pre-compresses that mount's text assets and stores only the
`.gz`. It is opt-in per mount because only one consumer can undo it: the HTTP
static handler, which probes `<path>.gz` and sets Content-Encoding. The shipped
programs and audio are read by loaders that would need a decompressor, so those
mounts stay raw - and the audio is already ADPCM, which does not compress
usefully anyway.

Stdlib only, and deliberately so: ESP-IDF already requires Python 3, so this
adds no build prerequisite. It also replaces the external `gzip` the staging
step used to shell out to - Python's gzip writes the same deflate stream and
takes `mtime=0`, which the command-line tool does not, so the same input now
produces the same bytes on every machine.

Determinism matters beyond tidiness: the blob's digest is what
`content.webapp.sha256` reports (#228), and a digest that changed because a
different gzip version was installed would say the bundle changed when it had
not.

Output: files concatenated at 4-byte-aligned offsets, and a header defining
RT_EMBEDDED_ENTRIES as an initialiser list of {path, offset, size}, sorted by
path.
"""

import gzip
import os
import sys

# Text assets are pre-compressed and only the `.gz` is shipped. The device has
# no CPU to spare compressing on the fly, and the vendored static handler
# already falls back to `<path>.gz` and sets Content-Encoding (see
# lib/psychic_http/src/PsychicStaticFileHandler.cpp) - so the on-device name
# keeping its `.gz` suffix is what makes this transparent.
#
# Images and fonts are skipped: PNG/ICO/WOFF are already compressed, so gzip
# would add a few percent and cost the device CPU to undo.
COMPRESSIBLE = {".js", ".css", ".html", ".json", ".svg", ".map", ".txt", ".xml"}

# The blob is read through a pointer into memory-mapped flash, so entries are
# aligned rather than packed tight. Four bytes is enough for every access this
# firmware makes of them (byte-wise reads through the VFS).
ALIGNMENT = 4


def c_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2
    out_bin, out_header = sys.argv[1], sys.argv[2]

    entries = []
    blob = bytearray()

    # Sorted, so the blob is byte-identical across machines and filesystems -
    # os.walk order is not defined. The mounts keep the order they were given:
    # it is the argument list, not the filesystem, so it is already stable.
    paths = []
    compressed_mounts = set()
    for spec in sys.argv[3:]:
        compress = spec.startswith("gz:")
        if compress:
            spec = spec[len("gz:") :]
        mount, _, root = spec.partition("=")
        if compress:
            compressed_mounts.add(mount)
        if not root or not os.path.isdir(root):
            continue
        found = []
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames.sort()
            for name in sorted(filenames):
                full = os.path.join(dirpath, name)
                rel = os.path.relpath(full, root).replace(os.sep, "/")
                found.append((f"/{mount}/{rel}", full))
        found.sort()
        paths.extend(found)

    for rel, path in paths:
        with open(path, "rb") as handle:
            data = handle.read()

        if rel.split("/")[1] in compressed_mounts and os.path.splitext(rel)[1].lower() in COMPRESSIBLE:
            # mtime=0 rather than the file's: the gzip header carries it, and a
            # rebuilt-but-identical file would otherwise change the digest.
            data = gzip.compress(data, compresslevel=9, mtime=0)
            rel += ".gz"

        padding = (-len(blob)) % ALIGNMENT
        blob.extend(b"\0" * padding)
        entries.append((rel, len(blob), len(data)))
        blob.extend(data)

    os.makedirs(os.path.dirname(out_bin) or ".", exist_ok=True)
    os.makedirs(os.path.dirname(out_header) or ".", exist_ok=True)

    # An empty blob still has to link: `.incbin` of a zero-byte file leaves
    # start == end, which is legal, but a zero-length C array is not - so the
    # index carries a sentinel entry instead of nothing.
    lines = [
        f'    {{"{c_escape(rel)}", {offset}, {size}}},' for rel, offset, size in entries
    ]
    if not lines:
        lines = ['    {"", 0, 0},']

    header = (
        "// Generated by firmware/tools/pack_assets.py - do not edit, do not commit.\n"
        "#pragma once\n"
        "\n"
        f"// {len(entries)} file(s), {len(blob)} bytes\n"
        "#define RT_EMBEDDED_ENTRIES \\\n" + " \\\n".join(lines) + "\n"
    )

    _write_if_changed(out_bin, bytes(blob))
    _write_if_changed(out_header, header.encode())

    total = sum(size for _, _, size in entries)
    print(f"Embedded {len(entries)} file(s), {total} bytes ({len(blob)} with alignment)")
    return 0


def _write_if_changed(path: str, data: bytes) -> None:
    """This runs on every build; rewriting an unchanged file would relink every time."""
    try:
        with open(path, "rb") as handle:
            if handle.read() == data:
                return
    except OSError:
        pass
    with open(path, "wb") as handle:
        handle.write(data)


if __name__ == "__main__":
    sys.exit(main())
